### ISSUE TITLE
Fix the URL Schema

### ISSUE THREAD

**Issue by adamdriscoll** [adamdriscoll/codegolf#18]
It would be nice to have a friendlier URL schema. All the GUIDs are hard to remember. Would be cool to type in the name of problems or users to head to the problem or profile.

**Comment by lazywinadmin** [comment]
@adamdriscoll Some sort of alias for the holes would be nice too, example: code-golf.com/h1 where h1 means hole#1

it is convenient for the discussions on twitter

**Comment by adamdriscoll** [comment]
@lazywinadmin Good idea! I'll think through it and propose something before I implement it all. I want to make sure the old links work too...

I hate ASP.NET routing...

**Comment by adamdriscoll** [comment]
Related to #17
